// hire.mn Test Database
// When AI recommends a test, it includes [TEST:id] markers
// The widget parses these and renders beautiful test cards

export interface TestInfo {
  id: number
  name: string
  nameEn: string
  desc: string
  descEn: string
  url: string
  price: string
  priceEn: string
  time: string
  emoji: string
  color: string
  tag: string
  tagEn: string
  category: "personality" | "health" | "behavior"
  image?: string
  // LLM-д өгөх дэлгэрэнгүй тайлбар — ямар асуудалд тохирох
  useCases: string
}

export const TEST_DATABASE: Record<number, TestInfo> = {
  1: {
    id: 1,
    name: "Өсөлтийн сэтгэлгээ (Mindset)",
    nameEn: "Growth Mindset Test",
    desc: "Өсөлтийн сэтгэлгээгээ мэдээрэх",
    descEn: "Discover your growth mindset potential",
    url: "https://hire.mn/test/1",
    price: "10,000",
    priceEn: "10,000",
    time: "10 мин",
    emoji: "🧗",
    color: "#E8541A",
    tag: "Aldartai",
    tagEn: "Popular",
    category: "personality",
    image: "/images/tests/test-1-growth-mindset.jpg",
    useCases: "Суралцахдаа бэрхшээлтэй, өөрийгөө хөгжүүлэхийг хүсдэг, амжилтгүй болохоос айдаг, шинэ зүйл сурахад хэцүү санагддаг, бүтэлгүйтлээс сэргийлэх",
  },
  2: {
    id: 2,
    name: "Ажил-амьдрал тэнцвэр",
    nameEn: "Work-Life Balance",
    desc: "Амьдралын тэнцвэрээр тайлбар ав",
    descEn: "Assess your work-life harmony",
    url: "https://hire.mn/test/2",
    price: "20,000",
    priceEn: "20,000",
    time: "10 мин",
    emoji: "⚖️",
    color: "#F0A830",
    tag: "Shine",
    tagEn: "New",
    category: "personality",
    image: "/images/tests/test-2-work-life-balance.jpg",
    useCases: "Ажилдаа их цаг зарцуулдаг, гэр бүлдээ цаг гаргаж чаддаггүй, ядарч түвддэг, стресстэй, burnout мэдрэмж, амралт авч чаддаггүй, ажил амьдралын хоорондох тэнцвэрээ олох",
  },
  3: {
    id: 3,
    name: "Харилцааны хэв шинж",
    nameEn: "Communication Style",
    desc: "Харилцааны өөрийн хэв шинжийг ойлго",
    descEn: "Understand your communication patterns",
    url: "https://hire.mn/test/3",
    price: "30,000",
    priceEn: "30,000",
    time: "10 мин",
    emoji: "💬",
    color: "#7C3AED",
    tag: "Udidrlagad",
    tagEn: "For Leaders",
    category: "behavior",
    image: "/images/tests/test-3-communication-style.jpg",
    useCases: "Хүмүүстэй харилцахад хэцүү, багаар ажиллахад асуудалтай, удирдах ажилтан, менежер, санаагаа илэрхийлж чаддаггүй, зөрчилдөөн шийдэж чаддаггүй, харилцааны ур чадвараа сайжруулах",
  },
  99: {
    id: 99,
    name: "AUDIT тест",
    nameEn: "AUDIT Test",
    desc: "Архины хэрэглээний үнэлгээ (WHO)",
    descEn: "Alcohol use assessment by WHO",
    url: "https://hire.mn/test/99",
    price: "Uneggui",
    priceEn: "Free",
    time: "10 мин",
    emoji: "🏥",
    color: "#E8A870",
    tag: "Uneggui",
    tagEn: "Free",
    category: "health",
    image: "/images/tests/test-99-audit.jpg",
    useCases: "Архи ууж байгаа, архины хэрэглээгээ хянах, согтууруулах ундаа хэт их хэрэглэж байгаа эсэх, архинд донтох эрсдэл, эрүүл мэндийн үзлэг",
  },
  5: {
    id: 5,
    name: "Никотин хамаарал",
    nameEn: "Nicotine Dependency",
    desc: "Тамхины хамаарлыг шалга",
    descEn: "Check your nicotine dependency level",
    url: "https://hire.mn/test/5",
    price: "Uneggui",
    priceEn: "Free",
    time: "10 мин",
    emoji: "🚭",
    color: "#64748B",
    tag: "Uneggui",
    tagEn: "Free",
    category: "health",
    image: "/images/tests/test-5-nicotine.jpg",
    useCases: "Тамхи татдаг, тамхинаас гарах гэж байгаа, тамхины хамаарлаа шалгах, никотин донтолт, эрүүл амьдралын хэв маягт шилжих",
  },
  6: {
    id: 6,
    name: "СЭМУТ урьдчилан сэргийлэх",
    nameEn: "SEMUT Screening",
    desc: "Сэтгэцийн эрүүл мэндийн шалгаруулалт",
    descEn: "Mental health preventive screening",
    url: "https://hire.mn/test/6",
    price: "Uneggui",
    priceEn: "Free",
    time: "25 мин",
    emoji: "🧘",
    color: "#EC4899",
    tag: "Chukhul",
    tagEn: "Important",
    category: "health",
    image: "/images/tests/test-6-semut.jpg",
    useCases: "Сэтгэл санаа муу, депресс мэдрэмж, санаа зовнил, уйтгар гунигтай, стресс ихтэй, сэтгэцийн эрүүл мэндээ шалгах, урьдчилан сэргийлэх, гутрал",
  },
  // Үнэгүй сорилтүүд
  7: {
    id: 7,
    name: "Өөртөө итгэх итгэл",
    nameEn: "Self-Confidence",
    desc: "Өөрийн өөртөө итгэх чадварыг үнэл",
    descEn: "Assess your self-confidence level",
    url: "https://hire.mn/test/7",
    price: "Uneggui",
    priceEn: "Free",
    time: "10 мин",
    emoji: "💪",
    color: "#06B6D4",
    tag: "Uneggui",
    tagEn: "Free",
    category: "personality",
    useCases: "Өөртөө итгэлгүй, ичимхий, олны өмнө ярихаас айдаг, шийдвэр гаргахад эргэлздэг, бусдын санаа бодлоос хэт ихээр хамаардаг, өөрийгөө үнэлдэггүй",
  },
  8: {
    id: 8,
    name: "Түгшүүрийн үнэлгээ",
    nameEn: "Anxiety Assessment",
    desc: "Түгшүүрийн түвшнийг хэмжээрэй",
    descEn: "Measure your anxiety level",
    url: "https://hire.mn/test/8",
    price: "Uneggui",
    priceEn: "Free",
    time: "10 мин",
    emoji: "😰",
    color: "#F59E0B",
    tag: "Uneggui",
    tagEn: "Free",
    category: "health",
    useCases: "Санаа зовнилтой, түгшүүртэй, сандрах, зүрхний цохилт түргэсдэг, нойргүй, хэт их бодолтой, ирээдүйгээсээ айдаг, panic attack, anxiety",
  },
  4: {
    id: 4,
    name: "Өөрийгөө үнэлэх (RSES)",
    nameEn: "Self-Esteem Test",
    desc: "Өөрийгөө үнэлэх чадвар",
    descEn: "Rosenberg Self-Esteem Scale",
    url: "https://hire.mn/test/4",
    price: "Uneggui",
    priceEn: "Free",
    time: "10 мин",
    emoji: "🌟",
    color: "#8B5CF6",
    tag: "Uneggui",
    tagEn: "Free",
    category: "personality",
    useCases: "Өөрийгөө үнэлж чаддаггүй, бусадтай харьцуулдаг, өөрийгөө дутуу санадаг, self-esteem бага, өөрийгөө хүндлэх, өөрийнхөө үнэ цэнийг мэдэхгүй",
  },
  // Төлбөртэй сорилтүүд
  10: {
    id: 10,
    name: "Тэсвэр тэвчээр (Grit)",
    nameEn: "Grit Test",
    desc: "Хүлээлцлийн чадварыг хэмжих",
    descEn: "Measure your perseverance",
    url: "https://hire.mn/test/10",
    price: "10,000",
    priceEn: "10,000",
    time: "10 мин",
    emoji: "🎯",
    color: "#DC2626",
    tag: "Premium",
    tagEn: "Premium",
    category: "personality",
    useCases: "Зорилгодоо хүрч чаддаггүй, амархан бууж өгдөг, тууштай байх, урт хугацааны зорилготой, хэцүү үед тэвчдэггүй, шаргуу хөдөлмөрлөх",
  },
  11: {
    id: 11,
    name: "Ёс зүйн манлайлал",
    nameEn: "Ethical Leadership",
    desc: "Ёс зүйн манлайлалын үнэлгээ",
    descEn: "Ethical leadership assessment",
    url: "https://hire.mn/test/11",
    price: "20,000",
    priceEn: "20,000",
    time: "20 мин",
    emoji: "⚖️",
    color: "#059669",
    tag: "Premium",
    tagEn: "Premium",
    category: "personality",
    useCases: "Удирдах ажилтан, менежер, манлайлагч, ёс зүйн асуудал, шийдвэр гаргалт, баг удирдах, ажлын байрны ёс зүй, leadership",
  },
  12: {
    id: 12,
    name: "16-н хэв шинж (Юнгийн тест)",
    nameEn: "16 Personality Types",
    desc: "Юнгийн хувь хүний типологи",
    descEn: "Jung's personality typing",
    url: "https://hire.mn/test/12",
    price: "20,000",
    priceEn: "20,000",
    time: "10 мин",
    emoji: "🧬",
    color: "#7C3AED",
    tag: "Premium",
    tagEn: "Premium",
    category: "personality",
    useCases: "Өөрийгөө илүү сайн ойлгох, хувь хүний хэв шинж, MBTI, introvert extravert, карьер сонголт, хамтрагчаа ойлгох, харилцаагаа сайжруулах",
  },
  
  // Нэмэлт тестүүд - useCases дэлгэрэнгүй
  13: {
    id: 13,
    name: "Багийн дүрийг тодорхойлох тест (Белбин)",
    nameEn: "Belbin Team Role Test",
    desc: "Өөрийнхөө багт оруулж буй хувь нэмрээ таньж мэдсэнээр...",
    descEn: "Discover your contribution to the team",
    url: "https://hire.mn/test/13",
    price: "30,000",
    priceEn: "30,000",
    time: "21 мин",
    emoji: "👥",
    color: "#3B82F6",
    tag: "Premium",
    tagEn: "Premium",
    category: "behavior",
    useCases: "Багаар ажиллах, багийн гишүүн, багийн дүр, Белбин, team role, хамтран ажиллах, багийн бүтэц, манлайлагч, гүйцэтгэгч, санаачлагч, шүүмжлэгч",
  },
  14: {
    id: 14,
    name: "Ажлын байран дээрх стресс",
    nameEn: "Workplace Stress Test",
    desc: "Ажлын байрны стрессийг илрүүлэх",
    descEn: "Identify workplace stress",
    url: "https://hire.mn/test/14",
    price: "Uneggui",
    priceEn: "Free",
    time: "15 мин",
    emoji: "😓",
    color: "#EF4444",
    tag: "Uneggui",
    tagEn: "Free",
    category: "health",
    useCases: "Ажилдаа стресстэй, ажлын ачаалал ихтэй, ажлаасаа ядардаг, burnout, ажлын байрны дарамт, ажил хаях гэсэн, ажлын орчин, даргатай харилцаа, хамт олонтой харилцаа",
  },
  15: {
    id: 15,
    name: "Сэтгэл хөдлөлийн оюун ухаан (EQ)",
    nameEn: "Emotional Intelligence (EQ)",
    desc: "Сэтгэл хөдлөлийн оюун ухааны үнэлгээ",
    descEn: "Emotional intelligence assessment",
    url: "https://hire.mn/test/15",
    price: "20,000",
    priceEn: "20,000",
    time: "20 мин",
    emoji: "❤️",
    color: "#EC4899",
    tag: "Premium",
    tagEn: "Premium",
    category: "personality",
    useCases: "Сэтгэл хөдлөлөө удирдах, бусдын сэтгэлийг ойлгох, EQ, emotional intelligence, empathy, өрөвдөх сэтгэл, удирдах ажилтан, харилцааны ур чадвар",
  },
  16: {
    id: 16,
    name: "Ажил мэргэжлийн сонирхол (RIASEC)",
    nameEn: "Career Interest (RIASEC)",
    desc: "Холландын мэргэжлийн сонирхлын тест",
    descEn: "Holland's career interest test",
    url: "https://hire.mn/test/16",
    price: "15,000",
    priceEn: "15,000",
    time: "20 мин",
    emoji: "🎯",
    color: "#10B981",
    tag: "Premium",
    tagEn: "Premium",
    category: "personality",
    useCases: "Ямар мэргэжил сонгох, карьер, ажил хайж байгаа, мэргэжлээ солих гэсэн, их сургуульд орох гэж байгаа, RIASEC, Holland, мэргэжлийн чиг баримжаа",
  },
  17: {
    id: 17,
    name: "Манлайллын хэв маяг",
    nameEn: "Leadership Style",
    desc: "Таны манлайллын хэв маягийг тодорхойлох",
    descEn: "Identify your leadership style",
    url: "https://hire.mn/test/17",
    price: "25,000",
    priceEn: "25,000",
    time: "15 мин",
    emoji: "👔",
    color: "#6366F1",
    tag: "Premium",
    tagEn: "Premium",
    category: "personality",
    useCases: "Удирдах ажилтан, менежер, баг удирдах, манлайлагч болох, удирдлагын ур чадвар, leadership, даргын албан тушаал, баг бүрдүүлэх",
  },
  18: {
    id: 18,
    name: "Депресс (PHQ-9)",
    nameEn: "Depression (PHQ-9)",
    desc: "Депрессийн түвшинг үнэлэх",
    descEn: "Depression level assessment",
    url: "https://hire.mn/test/18",
    price: "Uneggui",
    priceEn: "Free",
    time: "5 мин",
    emoji: "😔",
    color: "#6B7280",
    tag: "Uneggui",
    tagEn: "Free",
    category: "health",
    useCases: "Сэтгэл гутрал, депресс, уйтгар гуниг, сэтгэл санаа муу, амьдрах хүсэл алга, нойр хулжих, идэх дургүй, энерги алга, PHQ-9",
  },
  19: {
    id: 19,
    name: "Зан төлвийн DISC шинжилгээ",
    nameEn: "DISC Behavioral Analysis",
    desc: "DISC зан төлвийн загвар",
    descEn: "DISC behavioral model",
    url: "https://hire.mn/test/19",
    price: "30,000",
    priceEn: "30,000",
    time: "15 мин",
    emoji: "🔵",
    color: "#3B82F6",
    tag: "Premium",
    tagEn: "Premium",
    category: "behavior",
    useCases: "Зан төлөв, DISC, dominant, influence, steadiness, compliance, хүнтэй харилцах, ажлын хэв маяг, багийн гишүүдийг ойлгох",
  },
  20: {
    id: 20,
    name: "Сэтгэл зүйн аюулгүй орчин",
    nameEn: "Psychological Safety",
    desc: "Ажлын байрны сэтгэл зүйн аюулгүй байдал",
    descEn: "Workplace psychological safety",
    url: "https://hire.mn/test/20",
    price: "20,000",
    priceEn: "20,000",
    time: "10 мин",
    emoji: "🛡️",
    color: "#14B8A6",
    tag: "Premium",
    tagEn: "Premium",
    category: "health",
    useCases: "Ажлын байрны орчин, санаагаа чөлөөтэй хэлж чаддаггүй, алдаа гаргахаас айдаг, шүүмжлэлээс айдаг, багийн уур амьсгал, ажлын байрны соёл",
  },
  21: {
    id: 21,
    name: "Хэрэглээг үнэлэх тест",
    nameEn: "Substance Use Assessment",
    desc: "Бодис хэрэглээний үнэлгээ",
    descEn: "Substance use evaluation",
    url: "https://hire.mn/test/21",
    price: "Uneggui",
    priceEn: "Free",
    time: "10 мин",
    emoji: "💊",
    color: "#F97316",
    tag: "Uneggui",
    tagEn: "Free",
    category: "health",
    useCases: "Бодис хэрэглээ, донтолт, хар тамхи, мансууруулах бодис, хэрэглээгээ хянах, эмийн хэрэглээ, хамаарал, сэргээн засалт",
  },
  22: {
    id: 22,
    name: "Сэтгэл хөдлөлийн дүрэм",
    nameEn: "Emotion Regulation",
    desc: "Сэтгэл хөдлөлийг зохицуулах чадвар",
    descEn: "Emotion regulation skills",
    url: "https://hire.mn/test/22",
    price: "15,000",
    priceEn: "15,000",
    time: "15 мин",
    emoji: "🎭",
    color: "#A855F7",
    tag: "Premium",
    tagEn: "Premium",
    category: "personality",
    useCases: "Уурлах, сэтгэл хөдлөлөө удирдаж чаддаггүй, хэт их санаа зовох, стресстэй үед хэрхэн тайвширах, сэтгэл хөдлөлийн тэнцвэр",
  },
  23: {
    id: 23,
    name: "Олон оюуны үнэлгээ",
    nameEn: "Multiple Intelligence",
    desc: "Гарднерын олон оюуны онол",
    descEn: "Gardner's multiple intelligence theory",
    url: "https://hire.mn/test/23",
    price: "20,000",
    priceEn: "20,000",
    time: "25 мин",
    emoji: "🧩",
    color: "#F59E0B",
    tag: "Premium",
    tagEn: "Premium",
    category: "personality",
    useCases: "Оюуны чадвар, хэрхэн суралцах, давуу тал, сул тал, логик, хөгжим, байгаль, хүн хоорондын харилцаа, өөрийгөө таних",
  },
  24: {
    id: 24,
    name: "Зорилго тодорхойлох",
    nameEn: "Goal Setting",
    desc: "Зорилго тавих чадварын үнэлгээ",
    descEn: "Goal setting skills assessment",
    url: "https://hire.mn/test/24",
    price: "10,000",
    priceEn: "10,000",
    time: "10 мин",
    emoji: "🎯",
    color: "#22C55E",
    tag: "Premium",
    tagEn: "Premium",
    category: "personality",
    useCases: "Зорилгогүй, юу хийхээ мэдэхгүй, төлөвлөгөөгүй, амьдралын зорилго, карьерын зорилго, хувийн хөгжил, мотивац",
  },
  25: {
    id: 25,
    name: "Цаг удирдах чадвар",
    nameEn: "Time Management",
    desc: "Цаг баригч эсвэл хожимдогч?",
    descEn: "Time management skills",
    url: "https://hire.mn/test/25",
    price: "10,000",
    priceEn: "10,000",
    time: "10 мин",
    emoji: "⏰",
    color: "#0EA5E9",
    tag: "Premium",
    tagEn: "Premium",
    category: "personality",
    useCases: "Хожимддог, цагаа зөв хуваарилдаггүй, ажил дутуу хийдэг, эрэмбэлэх чадваргүй, цаг алдах, бүтээмж муу",
  },
  26: {
    id: 26,
    name: "Байгууллагын соёл (OCAI)",
    nameEn: "Organizational Culture (OCAI)",
    desc: "Байгууллагын соёлын үнэлгээ",
    descEn: "Organizational culture assessment",
    url: "https://hire.mn/test/26",
    price: "25,000",
    priceEn: "25,000",
    time: "20 мин",
    emoji: "🏢",
    color: "#8B5CF6",
    tag: "Premium",
    tagEn: "Premium",
    category: "behavior",
    useCases: "Байгууллагын соёл, компани, HR менежер, соёлыг өөрчлөх, ажлын орчин, OCAI, Cameron, Quinn",
  },
  27: {
    id: 27,
    name: "Уян хатан сэтгэлгээ",
    nameEn: "Resilience Test",
    desc: "Сэтгэл зүйн уян хатан байдал",
    descEn: "Psychological resilience",
    url: "https://hire.mn/test/27",
    price: "15,000",
    priceEn: "15,000",
    time: "15 мин",
    emoji: "🌱",
    color: "#10B981",
    tag: "Premium",
    tagEn: "Premium",
    category: "personality",
    useCases: "Хүндрэлийг даван туулах, бэрхшээлд дасах, уналтаас сэргэх, resilience, сэтгэл зүйн тэсвэр, стресстэй нөхцөлд ажиллах",
  },
  28: {
    id: 28,
    name: "Ажлын сэтгэл ханамж",
    nameEn: "Job Satisfaction",
    desc: "Ажилдаа хэр сэтгэл хангалуун байна вэ?",
    descEn: "How satisfied are you with your job?",
    url: "https://hire.mn/test/28",
    price: "Uneggui",
    priceEn: "Free",
    time: "10 мин",
    emoji: "😊",
    color: "#F59E0B",
    tag: "Uneggui",
    tagEn: "Free",
    category: "health",
    useCases: "Ажилдаа сэтгэл хангалуун бус, ажлаа солих гэсэн, ажилдаа дургүй, урам хугарсан, motivation алга, ажлын орчин муу",
  },
  29: {
    id: 29,
    name: "Зөрчилдөөн шийдвэрлэх хэв маяг",
    nameEn: "Conflict Resolution Style",
    desc: "Зөрчилдөөнийг хэрхэн шийдвэрлэдэг вэ?",
    descEn: "How do you handle conflicts?",
    url: "https://hire.mn/test/29",
    price: "20,000",
    priceEn: "20,000",
    time: "15 мин",
    emoji: "🤝",
    color: "#6366F1",
    tag: "Premium",
    tagEn: "Premium",
    category: "behavior",
    useCases: "Зөрчилдөөн, маргаан, хүмүүстэй зөрөлддөг, conflict, харилцааны асуудал, багийн зөрчил, шийдвэр гаргах",
  },
  30: {
    id: 30,
    name: "Хувийн үнэт зүйлс",
    nameEn: "Personal Values",
    desc: "Таны хувийн үнэт зүйлсийг тодорхойлох",
    descEn: "Identify your personal values",
    url: "https://hire.mn/test/30",
    price: "15,000",
    priceEn: "15,000",
    time: "15 мин",
    emoji: "💎",
    color: "#EC4899",
    tag: "Premium",
    tagEn: "Premium",
    category: "personality",
    useCases: "Үнэт зүйл, юу чухал вэ, амьдралын утга учир, values, зарчим, итгэл үнэмшил, шийдвэр гаргахад туслах",
  },
  31: {
    id: 31,
    name: "Хослол тохироо",
    nameEn: "Relationship Compatibility",
    desc: "Хосуудын тохироо",
    descEn: "Couple compatibility assessment",
    url: "https://hire.mn/test/31",
    price: "25,000",
    priceEn: "25,000",
    time: "20 мин",
    emoji: "💕",
    color: "#F43F5E",
    tag: "Premium",
    tagEn: "Premium",
    category: "behavior",
    useCases: "Хослол, хосын харилцаа, гэрлэх гэж байгаа, хамтрагчаа ойлгох, харилцаагаа сайжруулах, compatibility, love",
  },
  32: {
    id: 32,
    name: "Шийдвэр гаргах хэв маяг",
    nameEn: "Decision Making Style",
    desc: "Шийдвэр хэрхэн гаргадаг вэ?",
    descEn: "How do you make decisions?",
    url: "https://hire.mn/test/32",
    price: "15,000",
    priceEn: "15,000",
    time: "15 мин",
    emoji: "🤔",
    color: "#0891B2",
    tag: "Premium",
    tagEn: "Premium",
    category: "personality",
    useCases: "Шийдвэр гаргахад хэцүү, эргэлзээтэй, шийдвэр гаргах, decision making, сонголт хийх, удирдах ажилтан",
  },
  33: {
    id: 33,
    name: "Бүтээлч сэтгэлгээ",
    nameEn: "Creative Thinking",
    desc: "Бүтээлч сэтгэлгээний үнэлгээ",
    descEn: "Creative thinking assessment",
    url: "https://hire.mn/test/33",
    price: "20,000",
    priceEn: "20,000",
    time: "20 мин",
    emoji: "💡",
    color: "#FBBF24",
    tag: "Premium",
    tagEn: "Premium",
    category: "personality",
    useCases: "Бүтээлч, шинэ санаа, creativity, инноваци, асуудал шийдэх, дизайн, уран бүтээл, маркетинг",
  },
  34: {
    id: 34,
    name: "Нийгмийн дэмжлэг",
    nameEn: "Social Support",
    desc: "Нийгмийн дэмжлэгийн түвшин",
    descEn: "Social support level",
    url: "https://hire.mn/test/34",
    price: "Uneggui",
    priceEn: "Free",
    time: "10 мин",
    emoji: "🫂",
    color: "#8B5CF6",
    tag: "Uneggui",
    tagEn: "Free",
    category: "health",
    useCases: "Ганцаардал, найз нөхөдгүй, гэр бүл, дэмжлэг авах, нийгмийн сүлжээ, тусламж хэрэгтэй",
  },
  35: {
    id: 35,
    name: "Ажлын тэсвэр (Burnout)",
    nameEn: "Burnout Assessment",
    desc: "Ажлын тэсвэр хүлээц, шаталтын үнэлгээ",
    descEn: "Work burnout assessment",
    url: "https://hire.mn/test/35",
    price: "Uneggui",
    priceEn: "Free",
    time: "10 мин",
    emoji: "🔥",
    color: "#EF4444",
    tag: "Uneggui",
    tagEn: "Free",
    category: "health",
    useCases: "Burnout, шаталт, ажилдаа ядарсан, ажил хаях гэсэн, энерги алга, урам хугарсан, ажлын ачаалал",
  },
  36: {
    id: 36,
    name: "Сурах хэв маяг",
    nameEn: "Learning Style",
    desc: "Хэрхэн хамгийн сайн суралцдаг вэ?",
    descEn: "How do you learn best?",
    url: "https://hire.mn/test/36",
    price: "10,000",
    priceEn: "10,000",
    time: "15 мин",
    emoji: "📚",
    color: "#3B82F6",
    tag: "Premium",
    tagEn: "Premium",
    category: "personality",
    useCases: "Сурах, суралцах арга, visual, auditory, kinesthetic, оюутан, сургалт, хөгжил",
  },
  37: {
    id: 37,
    name: "Санхүүгийн зан үйл",
    nameEn: "Financial Behavior",
    desc: "Мөнгөтэй харьцах хэв маяг",
    descEn: "Money management behavior",
    url: "https://hire.mn/test/37",
    price: "15,000",
    priceEn: "15,000",
    time: "15 мин",
    emoji: "💰",
    color: "#10B981",
    tag: "Premium",
    tagEn: "Premium",
    category: "behavior",
    useCases: "Мөнгө, санхүү, хэмнэлт, зарлага, хэт их зардаг, мөнгө хүрдэггүй, санхүүгийн зан үйл",
  },
  38: {
    id: 38,
    name: "Ажил олгогчийн брэнд",
    nameEn: "Employer Brand",
    desc: "Ажил олгогчийн брэндийн үнэлгээ",
    descEn: "Employer brand assessment",
    url: "https://hire.mn/test/38",
    price: "50,000",
    priceEn: "50,000",
    time: "25 мин",
    emoji: "🏆",
    color: "#F59E0B",
    tag: "Premium",
    tagEn: "Premium",
    category: "behavior",
    useCases: "HR менежер, байгууллага, employer branding, ажилтан татах, ажлын байрны нэр хүнд",
  },
  39: {
    id: 39,
    name: "Хүүхдийн хөгжил",
    nameEn: "Child Development",
    desc: "Хүүхдийн хөгжлийн үнэлгээ (эцэг эхэд)",
    descEn: "Child development assessment for parents",
    url: "https://hire.mn/test/39",
    price: "20,000",
    priceEn: "20,000",
    time: "20 мин",
    emoji: "👶",
    color: "#EC4899",
    tag: "Premium",
    tagEn: "Premium",
    category: "personality",
    useCases: "Хүүхэд, эцэг эх, хүүхдийн хөгжил, сургуулийн өмнөх, эрт илрүүлэх, хүүхэд өсгөх",
  },
  40: {
    id: 40,
    name: "Нойрны чанар (PSQI)",
    nameEn: "Sleep Quality (PSQI)",
    desc: "Нойрны чанарын үнэлгээ",
    descEn: "Pittsburgh Sleep Quality Index",
    url: "https://hire.mn/test/40",
    price: "Uneggui",
    priceEn: "Free",
    time: "10 мин",
    emoji: "😴",
    color: "#6366F1",
    tag: "Uneggui",
    tagEn: "Free",
    category: "health",
    useCases: "Нойргүй, нойр хулжих, нойрны асуудал, унтаж чаддаггүй, нойрмоглох, сэрэх, PSQI",
  },
}

// Parse [TEST:id] markers from AI response and extract test IDs
export function parseTestMarkers(text: string): { cleanText: string; testIds: number[] } {
  const testIds: number[] = []
  const regex = /\[TEST:(\d+)\]/g
  let match

  while ((match = regex.exec(text)) !== null) {
    const id = parseInt(match[1], 10)
    if (TEST_DATABASE[id]) {
      testIds.push(id)
    }
  }

  const cleanText = text.replace(/\s*\[TEST:\d+\]/g, "").trim()
  return { cleanText, testIds }
}

export function getTestById(id: number): TestInfo | undefined {
  return TEST_DATABASE[id]
}

export function getTestsByCategory(category: TestInfo["category"]): TestInfo[] {
  return Object.values(TEST_DATABASE).filter((t) => t.category === category)
}

export function getFreeTests(): TestInfo[] {
  return Object.values(TEST_DATABASE).filter(
    (t) => t.price === "Uneggui" || t.priceEn === "Free"
  )
}
